### ISSUE TITLE
Getting Method Not Found Error

### ISSUE THREAD

**Issue by 54mv39** [redhat-developer/kestrel-linux-transport#78] opened 2019-07-16 12:57 UTC
<Method not found: 'Void Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.Internal.IConnectionDispatcher.OnConnection(Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.Internal.TransportConnection)'.
   at RedHat.AspNetCore.Server.Kestrel.Transport.Linux.TransportThread.ThreadContext.HandleAccept(TSocket tacceptSocket)
   at RedHat.AspNetCore.Server.Kestrel.Transport.Linux.TransportThread.ThreadContext.Run()
FailFast:
TransportThread

   at System.Environment.FailFast(System.String, System.Exception)
   at System.Environment.FailFast(System.String, System.Exception)
   at RedHat.AspNetCore.Server.Kestrel.Transport.Linux.TransportThread+ThreadContext.Run()
   at RedHat.AspNetCore.Server.Kestrel.Transport.Linux.TransportThread.PollThread(System.Object)
   at System.Threading.Thread.ThreadMain_ParameterizedThreadStart(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)

Exception details:
System.MissingMethodException: Method not found: 'Void Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.Internal.IConnectionDispatcher.OnConnection(Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.Internal.TransportConnection)'.
   at RedHat.AspNetCore.Server.Kestrel.Transport.Linux.TransportThread.ThreadContext.HandleAccept(TSocket tacceptSocket)
   at RedHat.AspNetCore.Server.Kestrel.Transport.Linux.TransportThread.ThreadContext.Run()>

**Comment by tmds** [comment] 2019-07-31 20:10
Is this a duplicate of https://github.com/redhat-developer/kestrel-linux-transport/issues/77?

What version of .NET Core are you using?

**Comment by 54mv39** [comment] 2019-08-01 11:31
Yeah its a duplicate. Some git hub issue at that time. sorry for that.

Here is my <dotnent --info> response:

<.NET Core SDK (reflecting any global.json):
 Version:   2.2.301
 Commit:    70d6be0814

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.2.301/

Host (useful for support):
  Version: 2.2.6
  Commit:  7dac9b1b51

.NET Core SDKs installed:
  2.2.301 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.6 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.6 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.6 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
root@localhost:~#
>

**Comment by tmds** [comment] 2019-08-01 14:49
What version of the kestrel-linux-transport are you using?

**Comment by 54mv39** [comment] 2019-08-01 14:51
`<PackageReference Include="RedHat.AspNetCore.Server.Kestrel.Transport.Linux" Version="2.1.0-preview1" />`

**Comment by tmds** [comment] 2019-08-01 17:30
> Version="2.1.0-preview1"

Try `Version="2.2.0-*"`

**Comment by 54mv39** [comment] 2019-08-02 07:57
That worked. Thanks.
So how do I get to which version to use since there is no indication as such in the docs?

**Comment by tmds** [comment] 2019-08-19 08:38
> Or are the version numbers set according to .net core version numbers and I should take hint from there?

Yes, you need to match the ASP.NET version _major.minor_.

**Closed by tmds** 2019-08-19 08:38 UTC

**Comment by Longnt1208** [comment] 2019-10-04 11:07
Hi tmds,

I have same issue, I tried change some version but still have missing method bug.
`.NET Core SDK (reflecting any global.json):
 Version:   2.2.402
 Commit:    c7f2f96116

Runtime Environment:
 OS Name:     centos
 OS Version:  7
 OS Platform: Linux
 RID:         centos.7-x64
 Base Path:   /usr/share/dotnet/sdk/2.2.402/

Host (useful for support):
  Version: 2.2.7
  Commit:  b1e29ae826

.NET Core SDKs installed:
  2.2.402 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]`

version I tried
- 2.2.1-190830-1096

> Method not found: 'Void Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.Internal.IConnectionDispatcher.OnConnection(Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.Internal.TransportConnection)'.
   at RedHat.AspNetCore.Server.Kestrel.Transport.Linux.TransportThread.ThreadContext.HandleAccept(TSocket tacceptSocket)
   at RedHat.AspNetCore.Server.Kestrel.Transport.Linux.TransportThread.ThreadContext.Run()

**Comment by 54mv39** [comment] 2019-10-04 11:19
@Longnt1208 As stated earlier in this issue... You should match the version number of the package to the Asp.Net Core runtime that you have installed on your system.

I see that you have runtime version 2.2.7
put like this in your csproj file: 
`<PackageReference Include="RedHat.AspNetCore.Server.Kestrel.Transport.Linux" Version="2.2.0-*" />`

**Comment by Longnt1208** [comment] 2019-10-04 11:49
Thanks @54mv39, this is my bad, I didn't overwrite new dll file after changed version. It's working now :)
